name: buzzword_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



  file_picker: ^5.4.0
  path_provider: ^2.0.14
  flutter_pdfview: ^1.4.0
  dio: ^5.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.2
  shared_preferences: ^2.0.17
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - asset/icons/
    - asset/images/